import { Plus, RotateCcw, Search } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { checkoutPages, transactions, webhooks } from "@/lib/demo-data";
export function CheckoutPagesList() { return <Module title="Checkout Pages" cta="New checkout" href="/dashboard/checkout-pages/new"><div className="grid gap-4 md:grid-cols-2">{checkoutPages.map((p) => <Card key={p}><CardContent className="p-5"><div className="flex items-start justify-between"><div><h3 className="font-semibold">{p}</h3><p className="mt-1 text-sm text-muted-foreground">zappo.co/pay/{p.toLowerCase().replaceAll(" ", "-")}</p></div><Badge variant="success">Published</Badge></div></CardContent></Card>)}</div></Module>; }
export function TransactionsPage() { return <Module title="Transactions" cta="Export CSV"><Card><CardContent className="p-0"><table className="w-full text-sm"><tbody>{transactions.map((t) => <tr key={t.id} className="border-b last:border-0"><td className="p-4 font-mono">{t.id}</td><td>{t.customer}</td><td>{t.amount}</td><td><Badge variant={t.status === "Successful" ? "success" : t.status === "Failed" ? "danger" : "warning"}>{t.status}</Badge></td><td>{t.gateway}</td><td>{t.date}</td></tr>)}</tbody></table></CardContent></Card></Module>; }
export function IntegrationsPage() { return <Module title="Integrations" cta="Verify all"><div className="grid gap-4 md:grid-cols-3">{["Flutterwave", "Kora", "PayPal"].map((p, i) => <Card key={p}><CardHeader><CardTitle>{p}</CardTitle></CardHeader><CardContent><Badge variant={i === 0 ? "success" : "warning"}>{i === 0 ? "Connected" : "Needs credentials"}</Badge><p className="mt-4 text-sm text-muted-foreground">Encrypted API credentials, test/live switching, webhook secret verification, and usage indicators.</p><Button className="mt-5 w-full" variant="outline">Configure</Button></CardContent></Card>)}</div></Module>; }
export function WebhooksPage() { return <Module title="Webhook monitoring" cta="Retry failures"><Card><CardContent className="p-0">{webhooks.map((w, i) => <div key={w} className="flex items-center justify-between border-b p-4 last:border-0"><div><p className="font-mono text-sm">{w}</p><p className="text-xs text-muted-foreground">Attempt #{i + 1} · signed payload · 428ms</p></div><Badge variant={i === 1 ? "danger" : "success"}>{i === 1 ? "Failed" : "Delivered"}</Badge><Button variant="ghost" size="icon"><RotateCcw className="size-4" /></Button></div>)}</CardContent></Card></Module>; }
export function GenericModule({ title }: { title: string }) { return <Module title={title} cta="Create"><div className="grid gap-4 md:grid-cols-3">{["Empty state", "Advanced filters", "Team-ready"].map((x) => <Card key={x}><CardContent className="p-6"><h3 className="font-semibold">{x}</h3><p className="mt-2 text-sm text-muted-foreground">Production-ready SaaS patterns with loading, empty, and permission-aware states.</p></CardContent></Card>)}</div></Module>; }
function Module({ title, cta, href, children }: { title: string; cta: string; href?: string; children: React.ReactNode }) { return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm text-muted-foreground">Dashboard / {title}</p><h1 className="text-4xl font-semibold tracking-tight">{title}</h1></div><div className="flex gap-2"><Button variant="outline"><Search className="size-4" /> Search</Button><Button asChild={Boolean(href)}>{href ? <Link href={href}><Plus className="size-4" /> {cta}</Link> : <span>{cta}</span>}</Button></div></div>{children}</div>; }
