import Link from "next/link";
import { ArrowRight, BarChart3, Check, Code2, Globe2, Lock, Repeat2, ShieldCheck, Sparkles, Workflow, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Logo } from "@/components/logo";
import { siteConfig } from "@/config/site";

export function MarketingHeader() {
  return <header className="sticky top-0 z-50 border-b bg-background/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><Logo /><nav className="hidden items-center gap-7 md:flex">{siteConfig.nav.map((n) => <Link key={n.href} href={n.href} className="text-sm text-muted-foreground hover:text-foreground">{n.label}</Link>)}</nav><div className="flex items-center gap-2"><Button asChild variant="ghost"><Link href="/login">Log in</Link></Button><Button asChild><Link href="/register">Start free</Link></Button></div></div></header>;
}

export function Hero() {
  return <section className="premium-gradient relative overflow-hidden"><div className="absolute inset-0 -z-10 bg-grid-fade [background-size:48px_48px] [mask-image:linear-gradient(to_bottom,black,transparent)]" /><div className="mx-auto grid max-w-7xl gap-12 px-4 py-24 lg:grid-cols-[1fr_0.9fr] lg:py-32"><div className="flex flex-col justify-center"><Badge className="mb-6 w-fit"><Sparkles className="mr-1 size-3" /> Seed-stage fintech polish for every merchant</Badge><h1 className="max-w-4xl text-balance text-5xl font-semibold tracking-[-0.04em] sm:text-7xl">Hosted checkout and payment links for Africa's next internet economy.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Create branded checkout pages, orchestrate Flutterwave, Kora, and PayPal, observe every webhook, and scale revenue operations from one premium command center.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" variant="gradient"><Link href="/register">Start Accepting Payments <ArrowRight className="size-4" /></Link></Button><Button asChild size="lg" variant="outline"><Link href="/dashboard/checkout-pages/new">Create Checkout Page</Link></Button></div><div className="mt-8 flex flex-wrap gap-3 text-sm text-muted-foreground"><span className="flex items-center gap-1"><ShieldCheck className="size-4 text-emerald-500" /> PCI-inspired patterns</span><span className="flex items-center gap-1"><Globe2 className="size-4 text-sky-500" /> NGN, GHS, KES, USD</span><span className="flex items-center gap-1"><Zap className="size-4 text-indigo-500" /> Edge-ready</span></div></div><CheckoutMockup /></div></section>;
}

function CheckoutMockup() {
  return <div className="glass rounded-[2rem] p-4 shadow-glow"><div className="rounded-[1.5rem] border bg-card p-5"><div className="flex items-center justify-between border-b pb-4"><Logo /><Badge variant="success">Live</Badge></div><div className="grid gap-4 py-5 sm:grid-cols-2"><Card className="bg-gradient-to-br from-indigo-600 to-sky-500 text-white"><CardContent className="p-5"><p className="text-sm/6 opacity-80">MRR collected</p><p className="mt-2 text-4xl font-semibold">$84.2k</p><div className="mt-8 h-20 rounded-xl bg-white/15" /></CardContent></Card><div className="space-y-3">{["Flutterwave", "Kora", "PayPal"].map((gateway, i) => <div key={gateway} className="flex items-center justify-between rounded-xl border bg-background p-3"><span className="font-medium">{gateway}</span><Badge variant={i === 0 ? "success" : "muted"}>{i === 0 ? "Primary" : "Fallback"}</Badge></div>)}</div></div><div className="rounded-2xl border bg-muted/40 p-4"><div className="mb-3 flex items-center justify-between"><span className="font-medium">Creator Pro checkout</span><span className="text-sm text-muted-foreground">98.4% uptime</span></div><div className="grid gap-3 sm:grid-cols-3">{["Email", "Card / mobile money", "Pay $49"].map((x) => <div key={x} className="rounded-xl bg-background p-3 text-sm shadow-sm">{x}</div>)}</div></div></div></div>;
}

export function LogoCloud() { return <section className="border-y bg-muted/30 py-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-8 px-4 text-sm font-semibold text-muted-foreground">{["Paystack alumni", "Lagos Labs", "Nairobi Cloud", "Accra Studio", "CreatorOS", "SaaS Guild"].map((x) => <span key={x}>{x}</span>)}</div></section>; }

export const features = [
  [Workflow, "Smart gateway routing", "Route payments by currency, uptime, fees, and customer location with deterministic fallback rules."],
  [BarChart3, "Revenue intelligence", "Beautiful cohort, funnel, and gateway analytics for operators and founders."],
  [Code2, "Developer-first APIs", "Typed SDK-ready responses, webhook retries, and auditable API keys from day one."],
  [Lock, "Secure credential vault", "Encrypted provider secrets, RBAC, audit logs, rate limiting, and secure headers."],
  [Repeat2, "Subscriptions", "Trials, billing intervals, retries, tax configuration, and multi-currency recurring revenue."],
  [Globe2, "Localized checkout", "Mobile-first experiences for cards, mobile money, PayPal, and regional customer details."],
] as const;

export function FeatureGrid() { return <section className="mx-auto max-w-7xl px-4 py-24"><div className="mx-auto max-w-2xl text-center"><Badge>Platform</Badge><h2 className="mt-4 text-4xl font-semibold tracking-tight">Everything needed to monetize globally and operate locally.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, desc]) => <Card key={title} className="group overflow-hidden"><CardContent className="p-6"><div className="mb-5 grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-indigo-600/15 to-sky-500/15 text-indigo-600 group-hover:scale-105"><Icon className="size-6" /></div><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{desc}</p></CardContent></Card>)}</div></section>; }

export function PricingCards() { const plans = [["Launch", "$0", ["3 checkout pages", "Payment links", "1 team member"]], ["Scale", "$29", ["Unlimited links", "Smart routing", "Webhook observability", "5 team members"]], ["Enterprise", "Custom", ["Custom domains", "Advanced RBAC", "Dedicated support"]]]; return <section className="mx-auto max-w-7xl px-4 py-24"><div className="text-center"><h2 className="text-4xl font-semibold tracking-tight">Pricing built for ambitious merchants</h2><p className="mt-3 text-muted-foreground">Start free. Upgrade when orchestration becomes mission-critical.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{plans.map(([name, price, items], i) => <Card key={name as string} className={i === 1 ? "border-indigo-500 shadow-glow" : ""}><CardContent className="p-6"><Badge variant={i === 1 ? "default" : "muted"}>{name}</Badge><p className="mt-5 text-4xl font-semibold">{price}<span className="text-sm font-normal text-muted-foreground">{price === "Custom" ? "" : "/mo"}</span></p><ul className="mt-6 space-y-3 text-sm">{(items as string[]).map((item) => <li key={item} className="flex gap-2"><Check className="size-4 text-emerald-500" /> {item}</li>)}</ul><Button className="mt-6 w-full" variant={i === 1 ? "gradient" : "outline"}>Choose {name}</Button></CardContent></Card>)}</div></section>; }

export function FAQ() { return <section className="mx-auto max-w-3xl px-4 py-20"><h2 className="text-center text-3xl font-semibold">Frequently asked questions</h2><div className="mt-8 space-y-3">{["Can I use Flutterwave and PayPal together?", "Do you support test mode?", "Can I invite my team?", "How are webhooks retried?"].map((q) => <details key={q} className="rounded-2xl border p-5"><summary className="cursor-pointer font-medium">{q}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">Yes. Zappo Checkout is designed for multi-provider orchestration with secure test/live credentials, workspace roles, and observable retry attempts.</p></details>)}</div></section>; }

export function MarketingFooter() { return <footer className="border-t py-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-4 text-sm text-muted-foreground md:flex-row"><Logo /><p>© 2026 Zappo Checkout. Built for modern fintech teams.</p></div></footer>; }
